spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: 123456
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
